"""User

Revision ID: 7cbfd536c0d0
Revises: 9a858698f85b
Create Date: 2023-11-07 22:53:50.288622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbfd536c0d0'
down_revision = '9a858698f85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_carpool')
    op.drop_table('search_student')
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))

    op.create_table('search_student',
    sa.Column('id_searchstudent', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_searchstudent'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id_searchstudent')
    )
    op.create_table('search_carpool',
    sa.Column('id_searchcarpool', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_searchcarpool'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id_searchcarpool')
    )
    # ### end Alembic commands ###
