"""Comment

Revision ID: d8feb5f7d049
Revises: 7cbfd536c0d0
Create Date: 2023-11-08 07:04:18.412583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8feb5f7d049'
down_revision = '7cbfd536c0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_text', sa.String(length=255), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('comment_text')

    # ### end Alembic commands ###
